name: Build APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Code
        run: cp app.py main.py || true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
      - name: Build Flet APK
        run: flet build apk --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: Abbas-App-APK
          path: build/apk/**/*.apk
