name: Build APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp app.py main.py || true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: pip install "flet[all]==0.23.2"
      - run: flet build apk --verbose
        env:
          FLET_CLI_NO_RICH_OUTPUT: "1"
          SERIOUS_PYTHON_ALLOW_SOURCE_DISTRIBUTIONS: "pyaes,pysocks"
      - uses: actions/upload-artifact@v4
        with:
          name: Abbas-App-APK
          path: build/apk/**/*.apk
